### ISSUE TITLE
Startup problem with Liferay 6.2 GA1 SP1

### ISSUE THREAD

**Issue by flaviusdaca** [permeance/liferay-webcontent-workflow-portlet#4]
The startup action throws a NPE at portal startup:

Feb 27, 2014 11:24:58 AM org.apache.catalina.core.StandardContext loadOnStartup
SEVERE: Servlet /webcontent-workflow-portlet threw load() exception
java.lang.NullPointerException
    at com.liferay.portal.kernel.workflow.WorkflowHandlerRegistryUtil.getWorkflowHandler(WorkflowHandlerRegistryUtil.java:47)
    at au.com.permeance.liferay.util.startup.StartupListener.applicationStart(StartupListener.java:52)
    at au.com.permeance.liferay.util.startup.StartupServlet.init(StartupServlet.java:39)
    at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1266)
    at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1185)
    at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1080)
    at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5015)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5302)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1095)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1617)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

**Comment by kostasLamogiannis** [comment]
Hi, same here using liferay 6.2, jbossa7 bundle, after restart:

19:21:27,833 INFO  [au.com.permeance.liferay.util.startup.StartupListener] (MSC service thread 1-8) Starting up Web Content Workflow Configuration Portlet
19:21:27,835 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/webcontent-workflow-portlet]] (MSC service thread 1-8) StandardWrapper.Throwable: java.lang.NullPointerException
	at com.liferay.portal.kernel.workflow.WorkflowHandlerRegistryUtil.getWorkflowHandler(WorkflowHandlerRegistryUtil.java:47) [portal-service.jar:]
	at au.com.permeance.liferay.util.startup.StartupListener.applicationStart(StartupListener.java:52) [classes:]
	at au.com.permeance.liferay.util.startup.StartupServlet.init(StartupServlet.java:39) [classes:]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1202) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1102) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3655) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3873) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]

19:21:27,857 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/webcontent-workflow-portlet]] (MSC service thread 1-8) Servlet /webcontent-workflow-portlet threw load() exception: java.lang.NullPointerException
	at com.liferay.portal.kernel.workflow.WorkflowHandlerRegistryUtil.getWorkflowHandler(WorkflowHandlerRegistryUtil.java:47) [portal-service.jar:]
	at au.com.permeance.liferay.util.startup.StartupListener.applicationStart(StartupListener.java:52) [classes:]
	at au.com.permeance.liferay.util.startup.StartupServlet.init(StartupServlet.java:39) [classes:]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1202) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1102) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3655) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3873) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]
